name: Static Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify-lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Verify if dependencies match yarn.lock
        run: yarn check --integrity

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Run ESLint
        run: yarn lint
